name = "FlakyTests"
uuid = "71f4a1cc-0e0b-4377-af3c-70be2a4aa85c"
authors = ["Marco Munizaga <git@marcopolo.io>"]
version = "0.1.0"

[deps]
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoSliderServer = "2fc8631c-6f24-4c5b-bca7-cbb509c42db4"
